### ISSUE TITLE
CPS2 - Blue Issue

### ISSUE THREAD

**Issue by Anselmo2004** [marqs85/cps2_digiav#7]
Recently I moved over my Cps2 board into a custom case. I noticed now that my BLUE color is off, it's actually too strong. All the colors are present, just blue is really high, like if it's bleeding over into the red,white, green color bars. I'll upload a picture of the issue, but is there a way to adjust individual colors somehow? something I should check?

**Comment by marqs85** [comment]
Sounds like one of the blue bit lines is stuck high / floating. Try checking that the socket (J1) is firmly connected to the board and respective header to MSM chip.

**Comment by Anselmo2004** [comment]
![20211103_090208](https://user-images.githubusercontent.com/93635186/140098788-c5dd40b7-fafd-4c0e-bd82-784da2d613c2.jpg)
![20211103_090303](https://user-images.githubusercontent.com/93635186/140098800-240efed7-61e0-4b08-a9b2-e8001de71561.jpg)

**Comment by Anselmo2004** [comment]
Thanks for the response. I've attached the pictures and I'll check your recommendations

**Comment by Anselmo2004** [comment]
Checking J1 I found a bad solder joint on the connector when checking each leg for continuity to the chip. Reflowed it and it's back to looking crispy! Thanks for the help and for the work. Greetings from Bakersfield  California!
