### ISSUE TITLE
Support for CPS 1.5 Q-Sound for Darksoft Multi Kit

### ISSUE THREAD

**Issue by lilo-san** [marqs85/cps2_digiav#8]
Currently this is probably the only missing bit to be able to make the ultimate CPS 1 console using this kit.

It is understandable that since the sound can come from either the A-Board or the B-Board when making the mod a switch to select the audio input for the DigitalAV board should be installed if need to avoid any interference.

**Comment by marqs85** [comment]
I've already designed an updated cps1_adapter for this purpose, will publish it once testing has been completed.

**Comment by zeldaconstruction** [comment]
Will be a new board or just an update? If is a new board where I can pre-order?

**Comment by lilo-san** [comment]
Will be a new board or just an update? If is a new board where I can pre-order?

**Comment by lilo-san** [comment]
Thanks for your quick response. If you made the adapter available for preorder please let me know.

**Comment by marqs85** [comment]
It will be new adapter PCB which is designed so that it could be ordered directly from JLCPCB as assembled.

**Comment by lilo-san** [comment]
Thanks for your quick response.

I will be waiting eagerly the update!

**Comment by lilo-san** [comment]
Any progress on the new cps1_adapter? Any news would be appreciated.

**Comment by marqs85** [comment]
I've not yet heard back from the person doing a test installation. I can share the design if you want to try yourself, but I can't guarantee its functionality.

**Comment by lilo-san** [comment]
I understand, maybe we can follow up this conversation on mail? lilo@lilo-co.almostmy.com

**Comment by marqs85** [comment]
This is now implemented in 6a7bf66bc1a7d012b20e8fcaaf8c5535ed85acb9
